# Setup
title: MR Lee
description: (AI) Developer. Engineer.
url: https://mrlee1102.github.io
avatar: /assets/avatar.jpg
paginate: 5
permalink: pretty
cover_image: /assets/bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
instargram:
  username: myeong._.ro
  card: summary
logo: logo.png
social:
  name: MR Lee
  links:
    - https://instagram.com/myeong._.ro
    - https://github.com/mrlee1102

lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
disqus: mrlee1102

# Specify the author for blog posts
author:
  name: MR Lee
  url: https://github.com/mrlee1102/
  email: leeroy7321@gmail.com
